"""empty message

Revision ID: 541a09bf22be
Revises: 290ded054ced
Create Date: 2020-05-17 20:48:14.168118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541a09bf22be'
down_revision = '290ded054ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.String(length=25), nullable=True))
    op.alter_column('Shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Shows', 'show_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('show_date', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.alter_column('Shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
