"""empty message

Revision ID: b5758e8413da
Revises: b22820b0225f
Create Date: 2020-05-13 05:59:23.921832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5758e8413da'
down_revision = 'b22820b0225f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.Column('venue_id', sa.Integer(), nullable=False),
                    sa.Column('show_date', sa.String(
                        length=25), nullable=True),
                    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
                    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_column('Artist', 'image_link')
    op.add_column('Venue', sa.Column(
        'genres', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('image_link', sa.VARCHAR(
        length=500), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres')
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(
        length=500), autoincrement=False, nullable=True))
    op.drop_table('Shows')
    # ### end Alembic commands ###
